title: "SelrahcD"
description: "Charles Desneuf's, SelrahcD, personal blog on development where he shares his ideas on Coding, Testing, DDD, Agile, Event Sourcing, CQRS, PHP, Elixir..."
#Comment out url when working locally to resolve base urls correctly
url: https://blog.charlesdesneuf.com
twitter:
  username: SelrahcD
  card: summary

# Owner/author information
owner:
  name:           Charles Desneuf
  avatar:         avatar.jpg
  bio: Charles Desneuf is a French developer, agile & architecture coach. He helps teams building product that serves the needs of its users.
  email:          c.desneuf@gmail.com
  twitter:        SelrahcD
  github:         selrahcd
  instagram:
  dribbble:
  disqus:         choripam

# Links to include in top navigation
# For external links add external: true
links:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    France/Paris
future:      true
markdown: kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  input: GFM
  syntax_highlighter: rouge


# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]

plugins:
  - jekyll-feed
  - jekyll-seo-tag


defaults:
  - scope:
      path: ""
    values:
      image: /images/avatar.jpeg